### ISSUE TITLE
can't start 'anaconda-mode' server

### ISSUE THREAD

**Issue by lyncisdev** [proofit404/anaconda-mode#285]
I cant seem to get the anaconda-mode functions to work, any definition look up i do i get an error in the mini-buffer saying `can't start 'anaconda-mode' server`

The error i get in the anaconda-mode buffer is:

```
Traceback (most recent call last):
  File "<string>", line 4, in <module>
  File "/home/lyncis/.local/lib/python2.7/site-packages/anaconda_mode.py", line 21, in <module>
    from jedi import Script, create_environment
  File "/home/lyncis/.local/lib/python2.7/site-packages/jedi/__init__.py", line 39, in <module>
    from jedi.api import Script, Interpreter, NotFoundError, set_debug_function
  File "/home/lyncis/.local/lib/python2.7/site-packages/jedi/api/__init__.py", line 21, in <module>
    from jedi.parser.user_context import UserContext, UserContextParser
  File "/home/lyncis/.local/lib/python2.7/site-packages/jedi/parser/user_context.py", line 11, in <module>
    from jedi.common import PushBackIterator
ImportError: cannot import name PushBackIterator


```

I'm using the default spacemacs Python layer.
Any help would be appreciated!

**Comment by proofit404** [comment]
Have no idea what the hell is going on.

**Comment by NathanLovato** [comment]
Started getting a similar error a few days ago:
```
Traceback (most recent call last):
  File "<string>", line 4, in <module>
  File "c:\Users\GDquest\AppData\Roaming\.emacs.d\.cache\anaconda-mode\0.1.11\anaconda_mode-0.1.11-py3.6.egg\anaconda_mode.py", line 21, in <module>
    from jedi import Script, create_environment
ImportError: cannot import name 'create_environment'
```
I couldn't find a workaround yet. Tried reinstalling etc. but no idea why this happened.

**Comment by NathanLovato** [comment]
I did that, used a fresh spacemacs install from git (stable), installed all packages, removed all user config too, same error:
```
Traceback (most recent call last):
  File "<string>", line 4, in <module>
  File "c:\Users\GDquest\AppData\Roaming\.emacs.d\.cache\anaconda-mode\0.1.11\anaconda_mode-0.1.11-py3.6.egg\anaconda_mode.py", line 21, in <module>
    from jedi import Script, create_environment
ImportError: cannot import name 'create_environment'
```

**Comment by NathanLovato** [comment]
I have jedi 0.11.0 installed globally, and there's a copy of jedi in the .cache folder of .emacs.d

![image](https://user-images.githubusercontent.com/12694995/40345100-c1cd7f04-5dd2-11e8-8e32-499c64529d3d.png)

I can import and access the jedi package no problem from my own python scripts. Any idea of other things I could try?

**Comment by lyncisdev** [comment]
Hi, I can second what NathanLovato said. I wiped the entire `.emacs.d` folder and reinstalled spacemacs and I still got the same error. I then cloned the anaconda-mode repo and tried to start the server manually, which worked for the session but now I'm getting other intermittent errors. So some of the time I have code-completion and sometime it produces an error. I'll post the error here when I get it next.

**Comment by lyncisdev** [comment]
This is the error I'm currently getting:

```
`127.0.0.1` - - [22/May/2018 12:47:03] ================================================================================
Traceback (most recent call last):
  File "/home/lyncis/.local/lib/python2.7/site-packages/service_factory/providers/basehttp.py", line 40, in do_POST
    status, response = self.server.service(data)
  File "/home/lyncis/.local/lib/python2.7/site-packages/service_factory/service.py", line 50, in __call__
    result = self.apply(method, args)
  File "/home/lyncis/.local/lib/python2.7/site-packages/service_factory/service.py", line 105, in apply
    server_error(args['id'], error)
  File "/home/lyncis/.local/lib/python2.7/site-packages/service_factory/errors.py", line 91, in server_error
    raise ServiceException(500, dumps(response))
ServiceException: (500, '{"jsonrpc": "2.0", "id": 1, "error": {"message": "Server error", "code": -32000, "data": "IOError(2, \'No such file or directory\')"}}')
```

**Comment by NathanLovato** [comment]
I updated the package today and the server works again. Thanks much @cjauvin and @proofit404 :)

**Comment by proofit404** [comment]
Good. Closing then.

**Comment by bryan-lott** [comment]
Unfortunately, I'm still getting the same error.  Would love to help diagnose what's wrong but I'm an emacs/spacemacs n00b.  Let me know what you need or how I can help.

The contents of my `*anaconda-mode*` buffer look like this:
```
[0;31mImportError[0m: cannot import name 'create_environment'
[0;31m[0m
[0;31mImportError[0mTraceback (most recent call last)
[0;32m<ipython-input-1-16a130d82445>[0m in [0;36m<module>[0;34m()[0m
[1;32m      4[0m [0msite[0m[0;34m.[0m[0maddsitedir[0m[0;34m([0m[0;34m'.'[0m[0;34m)[0m[0;34m[0m[0m
[1;32m      5[0m [0msys[0m[0;34m.[0m[0mpath[0m[0;34m.[0m[0mextend[0m[0;34m([0m[0mremainder[0m[0;34m)[0m[0;34m[0m[0m
[0;32m----> 6[0;31m [0;32mimport[0m [0manaconda_mode[0m[0;34m[0m[0m
[0m[1;32m      7[0m [0manaconda_mode[0m[0;34m.[0m[0mmain[0m[0;34m([0m[0msys[0m[0;34m.[0m[0margv[0m[0;34m[[0m[0;34m-[0m[0;36m2[0m[0;34m:[0m[0;34m][0m[0;34m)[0m[0;34m[0m[0m

[0;32m~/.emacs.d/.cache/anaconda-mode/0.1.11/anaconda_mode-0.1.11-py3.6.egg/anaconda_mode.py[0m in [0;36m<module>[0;34m()[0m
[1;32m     19[0m [0;32mfrom[0m [0mfunctools[0m [0;32mimport[0m [0mwraps[0m[0;34m[0m[0m
[1;32m     20[0m [0;34m[0m[0m
[0;32m---> 21[0;31m [0;32mfrom[0m [0mjedi[0m [0;32mimport[0m [0mScript[0m[0;34m,[0m [0mcreate_environment[0m[0;34m[0m[0m
[0m[1;32m     22[0m [0;32mfrom[0m [0mservice_factory[0m [0;32mimport[0m [0mservice_factory[0m[0;34m[0m[0m
[1;32m     23[0m [0;34m[0m[0m

[0;31mImportError[0m: cannot import name 'create_environment'
```

**Comment by proofit404** [comment]
Can you provide `tree` output of the ~/.emacs.d/.cache/anaconda-mode/0.1.11/

**Comment by bryan-lott** [comment]
```
.
├── anaconda_mode-0.1.11-py3.6.egg
│   ├── EGG-INFO
│   │   ├── PKG-INFO
│   │   ├── RECORD
│   │   ├── WHEEL
│   │   ├── requires.txt
│   │   └── top_level.txt
│   ├── __pycache__
│   │   └── anaconda_mode.cpython-36.pyc
│   └── anaconda_mode.py
├── easy-install.pth
├── jedi-0.12.0-py3.6.egg
│   ├── EGG-INFO
│   │   ├── DESCRIPTION.rst
│   │   ├── PKG-INFO
│   │   ├── RECORD
│   │   ├── WHEEL
│   │   ├── metadata.json
│   │   ├── requires.txt
│   │   └── top_level.txt
│   └── jedi
│       ├── __init__.py
│       ├── __main__.py
│       ├── _compatibility.py
│       ├── api
│       │   ├── __init__.py
│       │   ├── classes.py
│       │   ├── completion.py
│       │   ├── environment.py
│       │   ├── exceptions.py
│       │   ├── helpers.py
│       │   ├── interpreter.py
│       │   ├── keywords.py
│       │   ├── project.py
│       │   └── replstartup.py
│       ├── cache.py
│       ├── common
│       │   ├── __init__.py
│       │   ├── context.py
│       │   └── utils.py
│       ├── debug.py
│       ├── evaluate
│       │   ├── __init__.py
│       │   ├── analysis.py
│       │   ├── arguments.py
│       │   ├── base_context.py
│       │   ├── cache.py
│       │   ├── compiled
│       │   │   ├── __init__.py
│       │   │   ├── access.py
│       │   │   ├── context.py
│       │   │   ├── fake
│       │   │   │   ├── _functools.pym
│       │   │   │   ├── _sqlite3.pym
│       │   │   │   ├── _sre.pym
│       │   │   │   ├── _weakref.pym
│       │   │   │   ├── builtins.pym
│       │   │   │   ├── datetime.pym
│       │   │   │   ├── io.pym
│       │   │   │   ├── operator.pym
│       │   │   │   └── posix.pym
│       │   │   ├── fake.py
│       │   │   ├── getattr_static.py
│       │   │   ├── mixed.py
│       │   │   └── subprocess
│       │   │       ├── __init__.py
│       │   │       ├── __main__.py
│       │   │       └── functions.py
│       │   ├── context
│       │   │   ├── __init__.py
│       │   │   ├── asynchronous.py
│       │   │   ├── function.py
│       │   │   ├── instance.py
│       │   │   ├── iterable.py
│       │   │   ├── klass.py
│       │   │   ├── module.py
│       │   │   └── namespace.py
│       │   ├── docstrings.py
│       │   ├── dynamic.py
│       │   ├── filters.py
│       │   ├── finder.py
│       │   ├── flow_analysis.py
│       │   ├── helpers.py
│       │   ├── imports.py
│       │   ├── jedi_typing.py
│       │   ├── lazy_context.py
│       │   ├── param.py
│       │   ├── parser_cache.py
│       │   ├── pep0484.py
│       │   ├── recursion.py
│       │   ├── stdlib.py
│       │   ├── syntax_tree.py
│       │   ├── sys_path.py
│       │   ├── usages.py
│       │   └── utils.py
│       ├── parser_utils.py
│       ├── refactoring.py
│       ├── settings.py
│       └── utils.py
├── parso-0.2.1-py3.6.egg
│   ├── EGG-INFO
│   │   ├── DESCRIPTION.rst
│   │   ├── PKG-INFO
│   │   ├── RECORD
│   │   ├── WHEEL
│   │   ├── metadata.json
│   │   └── top_level.txt
│   └── parso
│       ├── __init__.py
│       ├── _compatibility.py
│       ├── cache.py
│       ├── grammar.py
│       ├── normalizer.py
│       ├── parser.py
│       ├── pgen2
│       │   ├── __init__.py
│       │   ├── grammar.py
│       │   ├── parse.py
│       │   └── pgen.py
│       ├── python
│       │   ├── __init__.py
│       │   ├── diff.py
│       │   ├── errors.py
│       │   ├── grammar26.txt
│       │   ├── grammar27.txt
│       │   ├── grammar33.txt
│       │   ├── grammar34.txt
│       │   ├── grammar35.txt
│       │   ├── grammar36.txt
│       │   ├── grammar37.txt
│       │   ├── parser.py
│       │   ├── pep8.py
│       │   ├── prefix.py
│       │   ├── token.py
│       │   ├── tokenize.py
│       │   └── tree.py
│       ├── tree.py
│       └── utils.py
└── service_factory-0.1.5-py3.6.egg
    ├── EGG-INFO
    │   ├── DESCRIPTION.rst
    │   ├── PKG-INFO
    │   ├── RECORD
    │   ├── WHEEL
    │   ├── metadata.json
    │   └── top_level.txt
    └── service_factory
        ├── __init__.py
        ├── compat.py
        ├── errors.py
        ├── exceptions.py
        ├── factory.py
        ├── providers
        │   ├── __init__.py
        │   └── basehttp.py
        ├── service.py
        └── validation.py
```

**Comment by bryan-lott** [comment]
Managed to solve it for me by upgrading my version of Jedi to 0.12.0.  Still points to an import issue.

**Comment by cjauvin** [comment]
@bryan-lott What exact version of anaconda-mode are you running? The problem with the Jedi version has been solved in what is currently the [tip](https://github.com/proofit404/anaconda-mode/commit/c5e7c62e517af228047bce16c4599cdac54fec94) of the master branch, and has not been officially released yet. You can get the freshest version on [MELPA](https://melpa.org/packages/anaconda-mode-20180522.2133.el).

**Comment by bryan-lott** [comment]
`M-x list-packages` gives me a version of `20180522.2133`
